version: '3'
services:
  app:
    build:
      context: '.'
    ports:
      - 4000:4000
    environment:
      OIDC_URL: 'https://keycloak.mortenolsen.pro/auth/realms/master'
      OIDC_CLIENT_ID: 'test'
